export const PHOTOS_BEFORE_UPLOAD = 'PHOTOS_BEFORE_UPLOAD';
export const PHOTOS_ERROR_UPLOAD = 'PHOTOS_ERROR_UPLOAD';
export const PHOTOS_AFTER_UPLOAD = 'PHOTOS_AFTER_UPLOAD';

export const PHOTOS_BEFORE_DELETE = 'PHOTOS_BEFORE_DELETE';
export const PHOTOS_AFTER_DELETE = 'PHOTOS_AFTER_DELETE';
export const PHOTOS_ERROR_DELETE = 'PHOTOS_ERROR_DELETE';

export const PHOTOS_BEFORE_SET_AS_AVATAR = 'PHOTOS_BEFORE_SET_AS_AVATAR';
export const PHOTOS_AFTER_SET_AS_AVATAR = 'PHOTOS_AFTER_SET_AS_AVATAR';
export const PHOTOS_ERROR_SET_AS_AVATAR = 'PHOTOS_ERROR_SET_AS_AVATAR';
