export const APPLICATION_SET_LANGUAGE = 'APPLICATION_SET_LANGUAGE';
export const APPLICATION_SET_LANGUAGE_DIRECTION = 'APPLICATION_SET_LANGUAGE_DIRECTION';
export const APPLICATION_SET_LOCATION = 'APPLICATION_SET_LOCATION';
export const APPLICATION_RESET = 'APPLICATION_RESET';