export const CONVERSATIONS_SET = 'CONVERSATIONS_SET';

export const CONVERSATIONS_BEFORE_DELETE = 'CONVERSATIONS_BEFORE_DELETE';
export const CONVERSATIONS_AFTER_DELETE = 'CONVERSATIONS_AFTER_DELETE';
export const CONVERSATIONS_ERROR_DELETE = 'CONVERSATIONS_ERROR_DELETE';

export const CONVERSATIONS_BEFORE_MARK_READ = 'CONVERSATIONS_BEFORE_MARK_READ';
export const CONVERSATIONS_AFTER_MARK_READ = 'CONVERSATIONS_AFTER_MARK_READ';
export const CONVERSATIONS_ERROR_MARK_READ = 'CONVERSATIONS_ERROR_MARK_READ';

export const CONVERSATIONS_BEFORE_MARK_UNREAD = 'CONVERSATIONS_BEFORE_MARK_UNREAD';
export const CONVERSATIONS_AFTER_MARK_UNREAD = 'CONVERSATIONS_AFTER_MARK_UNREAD';
export const CONVERSATIONS_ERROR_MARK_UNREAD = 'CONVERSATIONS_ERROR_MARK_UNREAD';
