export const HOT_LIST_SET = 'HOT_LIST_SET';
export const HOT_LIST_BEFORE_DELETE = 'HOT_LIST_BEFORE_DELETE';
export const HOT_LIST_AFTER_DELETE = 'HOT_LIST_AFTER_DELETE';
export const HOT_LIST_ERROR_DELETE = 'HOT_LIST_ERROR_DELETE';
export const HOT_LIST_BEFORE_ADD = 'HOT_LIST_BEFORE_ADD';
export const HOT_LIST_AFTER_ADD = 'HOT_LIST_AFTER_ADD';
export const HOT_LIST_ERROR_ADD = 'HOT_LIST_ERROR_ADD';
