export const VIDEO_IM_ADD_NOTIFICATION = 'VIDEO_IM_ADD_NOTIFICATION';
export const VIDEO_IM_BEFORE_MARK_NOTIFICATION = 'VIDEO_IM_BEFORE_MARK_NOTIFICATION';
export const VIDEO_IM_AFTER_MARK_NOTIFICATION = 'VIDEO_IM_AFTER_MARK_NOTIFICATION';
export const VIDEO_IM_ERROR_MARK_NOTIFICATION = 'VIDEO_IM_ERROR_MARK_NOTIFICATION';
export const VIDEO_IM_SET_ACTIVE_INTERLOCUTOR_DATA = 'VIDEO_IM_SET_ACTIVE_INTERLOCUTOR_DATA';
export const VIDEO_IM_SET_INTERLOCUTOR_SESSION_ID = 'VIDEO_IM_SET_INTERLOCUTOR_SESSION_ID';
export const VIDEO_IM_REMOVE_INTERLOCUTOR_SESSION_ID = 'VIDEO_IM_REMOVE_INTERLOCUTOR_SESSION_ID';