export const MATCHED_USERS_SET = 'MATCHED_USERS_SET';

export const MATCHED_USERS_BEFORE_MARK_NOTIFIED = 'MATCHED_USERS_BEFORE_MARK_NOTIFIED';
export const MATCHED_USERS_AFTER_MARK_NOTIFIED = 'MATCHED_USERS_AFTER_MARK_NOTIFIED';
export const MATCHED_USERS_ERROR_MARK_NOTIFIED = 'MATCHED_USERS_ERROR_MARK_NOTIFIED';

export const MATCHED_USERS_BEFORE_MARK_READ = 'MATCHED_USERS_BEFORE_MARK_READ';
export const MATCHED_USERS_AFTER_MARK_READ = 'MATCHED_USERS_AFTER_MARK_READ';
export const MATCHED_USERS_ERROR_MARK_READ = 'MATCHED_USERS_ERROR_MARK_READ';
