export const AVATARS_BEFORE_UPLOAD = 'AVATARS_BEFORE_UPLOAD';
export const AVATARS_ERROR_UPLOAD = 'AVATARS_ERROR_UPLOAD';
export const AVATARS_AFTER_UPLOAD = 'AVATARS_AFTER_UPLOAD';

export const AVATARS_BEFORE_DELETE = 'AVATARS_BEFORE_DELETE';
export const AVATARS_AFTER_DELETE = 'AVATARS_AFTER_DELETE';
export const AVATARS_ERROR_DELETE = 'AVATARS_ERROR_DELETE';
