export const MATCH_ACTIONS_BEFORE_ADD = 'MATCH_ACTIONS_BEFORE_ADD';
export const MATCH_ACTIONS_AFTER_ADD = 'MATCH_ACTIONS_AFTER_ADD';
export const MATCH_ACTIONS_ERROR_ADD = 'MATCH_ACTIONS_ERROR_ADD';

export const MATCH_ACTIONS_BEFORE_DELETE = 'MATCH_ACTIONS_BEFORE_DELETE';
export const MATCH_ACTIONS_AFTER_DELETE = 'MATCH_ACTIONS_AFTER_DELETE';
export const MATCH_ACTIONS_ERROR_DELETE = 'MATCH_ACTIONS_ERROR_DELETE';
