export const BOOKMARKS_LOAD = 'BOOKMARKS_LOAD';

export const BOOKMARKS_BEFORE_DELETE = 'BOOKMARKS_BEFORE_DELETE';
export const BOOKMARKS_AFTER_DELETE = 'BOOKMARKS_AFTER_DELETE';
export const BOOKMARKS_ERROR_DELETE = 'BOOKMARKS_ERROR_DELETE';

export const BOOKMARKS_BEFORE_ADD = 'BOOKMARKS_BEFORE_ADD';
export const BOOKMARKS_AFTER_ADD = 'BOOKMARKS_AFTER_ADD';
export const BOOKMARKS_ERROR_ADD = 'BOOKMARKS_ERROR_ADD';
