export const GUESTS_SET = 'GUESTS_SET';
export const GUESTS_BEFORE_DELETE = 'GUESTS_BEFORE_DELETE';
export const GUESTS_AFTER_DELETE = 'GUESTS_AFTER_DELETE';
export const GUESTS_ERROR_DELETE = 'GUESTS_ERROR_DELETE';
export const GUESTS_MARK_READ = 'GUESTS_MARK_READ';
export const GUESTS_MARK_ALL_NOTIFIED = 'GUESTS_MARK_ALL_NOTIFIED';

export const GUESTS_BEFORE_MARK_ALL_READ = 'GUESTS_BEFORE_MARK_ALL_READ';
export const GUESTS_AFTER_MARK_ALL_READ = 'GUESTS_AFTER_MARK_ALL_READ';
export const GUESTS_ERROR_MARK_ALL_READ = 'GUESTS_ERROR_MARK_ALL_READ';