export const USERS_LOAD = 'USERS_LOAD';
export const USERS_LOGOUT = 'USERS_LOGOUT';

export const USERS_BEFORE_BLOCK = 'USERS_BEFORE_BLOCK';
export const USERS_AFTER_BLOCK = 'USERS_AFTER_BLOCK';
export const USERS_ERROR_BLOCK = 'USERS_ERROR_BLOCK';

export const USERS_BEFORE_UNBLOCK = 'USERS_BEFORE_UNBLOCK';
export const USERS_AFTER_UNBLOCK = 'USERS_AFTER_UNBLOCK';
export const USERS_ERROR_UNBLOCK = 'USERS_ERROR_UNBLOCK';
